/// This file is a part of media_kit (https://github.com/media-kit/media-kit).
///
/// Copyright © 2021 & onwards, Hitesh Kumar Saini <saini123hitesh@gmail.com>.
/// All rights reserved.
/// Use of this source code is governed by MIT license that can be found in the LICENSE file.

import 'dart:async';

/// State of an FFmpeg execution session.
enum SessionState {
  created,
  running,
  completed,
  failed,
}

/// A session encapsulates the execution of an FFmpeg command.
class FFmpegSession {
  /// Unique identifier for the session.
  final int sessionId;

  /// The arguments passed to the FFmpeg command.
  final List<String> arguments;

  /// The logs generated by the execution.
  final List<String> _logs = [];

  /// The creation time of the session.
  final DateTime creationTime;

  /// The start time of the execution.
  DateTime? startTime;

  /// The end time of the execution.
  DateTime? endTime;

  /// The return code of the execution.
  Completer<int> _returnCodeCompleter = Completer<int>();

  /// The current state of the session.
  SessionState _state = SessionState.created;

  /// Stream controller for log messages.
  final StreamController<String> _logStreamController =
      StreamController<String>.broadcast();

  FFmpegSession(this.arguments)
      : sessionId = DateTime.now().millisecondsSinceEpoch,
        creationTime = DateTime.now();

  /// Returns the logs generated by the execution.
  List<String> getLogs() => List.unmodifiable(_logs);

  /// Returns a stream of log messages.
  Stream<String> getLogStream() => _logStreamController.stream;

  /// Returns the future of the return code.
  Future<ReturnCode> getReturnCode() async {
    final code = await _returnCodeCompleter.future;
    return ReturnCode(code);
  }

  /// Returns the current state of the session.
  SessionState getState() => _state;

  /// (Internal) Adds a log message to the session.
  void addLog(String log) {
    _logs.add(log);
    _logStreamController.add(log);
  }

  /// (Internal) Sets the return code of the session and marks it as completed.
  void complete(int returnCode) {
    if (_returnCodeCompleter.isCompleted) return;
    _returnCodeCompleter.complete(returnCode);
    _state = returnCode == 0 ? SessionState.completed : SessionState.failed;
    endTime = DateTime.now();
    _logStreamController.close();
  }

  /// (Internal) Marks the session as running.
  void start() {
    _state = SessionState.running;
    startTime = DateTime.now();
  }
}

/// Helper class to handle FFmpeg return codes.
class ReturnCode {
  static const int success = 0;
  static const int cancel = 255;

  final int _value;

  ReturnCode(this._value);

  static bool isSuccess(ReturnCode? returnCode) =>
      returnCode?.getValue() == ReturnCode.success;

  static bool isCancel(ReturnCode? returnCode) =>
      returnCode?.getValue() == ReturnCode.cancel;

  int getValue() => _value;

  bool isValueSuccess() => _value == ReturnCode.success;

  bool isValueError() =>
      (_value != ReturnCode.success) && (_value != ReturnCode.cancel);

  bool isValueCancel() => _value == ReturnCode.cancel;

  @override
  String toString() => _value.toString();
}
